version: 2.0

jobs:
    build:
        steps:
            - checkout
                - run:
          command: | ./gradlew bootjar
            - save_cache:
                paths:
                    - ~/.gradle
                key: gradle-{{ checksum "build.gradle" }}
            - store_artifacts:
                path: build/distributions
                destination: distributions
            - store_artifacts:
                path: build/libs
                destination: libs
